version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'grocery_store'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
