version: '3'

services:
  seed:
    build: .
    restart: always
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
